#!/bin/sh

set -e

(
echo "[ ] Downloading manifest..."
export MANIFEST_JSON='{ "id": "torrserv.matrix.app", "version": "0.3.6", "type": "native", "title": "Torrserver MatriX", "appDescription": "Torrent stream server for webOS", "iconUri": "https://webosappclub.github.io/apps/torrserv.matrix.app/icon.png", "sourceUrl": "https://github.com/YouROK/TorrServer", "rootRequired": false, "ipkUrl": "https://webosappclub.github.io/apps/torrserv.matrix.app/torrserv.matrix.app_0.3.6_all.ipk", "ipkHash": { "sha256": "013e98c0f0d39f2351961f1a292db0f043ff61354e39e89813dfc4ca19a74fb0" }, "ipkSize": 14572046 }'

export $(node -e '
var manifest = JSON.parse(process.env.MANIFEST_JSON);
console.info("IPK_URL=" + require("url").resolve(process.env.MANIFEST_URL, manifest.ipkUrl));
console.info("IPK_SHA256=" + manifest.ipkHash.sha256);
')

echo "[ ] Downloading $IPK_URL..."
curl -L -o /tmp/hbchannel.ipk -- "$IPK_URL"
echo "$IPK_SHA256  /tmp/hbchannel.ipk" | sha256sum -c

rm -rf /tmp/luna-install
mkfifo /tmp/luna-install
echo "[ ] Installing..."
luna-send-pub -w 15000 -i 'luna://com.webos.appInstallService/dev/install' '{"id":"com.ares.defaultName","ipkUrl":"/tmp/hbchannel.ipk","subscribe":true}' >/tmp/luna-install &
LUNA_PID=$!

if ! result="$(fgrep -m 1 -e 'installed' -e 'failed' /tmp/luna-install)"; then
    rm /tmp/luna-install
    echo "[!] Install timed out"
    exit 1
fi

kill -TERM "$LUNA_PID" 2>/dev/null || true
rm /tmp/luna-install

case "$result" in
    *installed*) ;;
    *)
        echo "[!] Install failed - $result"
        exit 1
    ;;
esac

/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/elevate-service || echo "[!] Elevation failed - is Your TV rooted?"

echo
echo "[*]"
echo "[*] Homebrew Channel Installed!"
echo "[*]"
echo
)
